package easy.work.source.module.rights.dao;

import java.util.List;

import easy.work.source.module.rights.pojo.MenuPermission;

public interface MenuPermissionDao {
	
	/**
	 * @Auther: zhuwt  
	 * @Description: 批量删除 菜单
	 * @Date:2017年5月27日下午6:27:33
	 * @param ids
	 * @return  
	 * @return int
	 */
	int deleteByPids(Integer[] ids);
	
	/**
	 * @Auther: zhuwt  
	 * @Description: 批量删除 权限 
	 * @Date:2017年5月27日下午6:27:08
	 * @param ids
	 * @return  
	 * @return int
	 */
	int deleteByMids(List<Integer> ids);

	/**
	 * @Auther: zhuwt
	 * @Description: 根据权限pid删除数据
	 * @Date:2017年5月23日上午1:35:45
	 * @param pid
	 * @return
	 * @return Integer
	 */
	Integer deleteByPid(int pid);

	/**
	 * @Auther: zhuwt
	 * @Description: 修改数据
	 * @Date:2017年5月23日上午1:38:18
	 * @param pid
	 * @return
	 * @return Integer
	 */
	Integer updateByPid(MenuPermission menuPermission);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table menu_permission
	 *
	 * @mbg.generated Tue May 23 01:24:41 CST 2017
	 */
	int deleteByPrimaryKey(Integer menuPermissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table menu_permission
	 *
	 * @mbg.generated Tue May 23 01:24:41 CST 2017
	 */
	int insert(MenuPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table menu_permission
	 *
	 * @mbg.generated Tue May 23 01:24:41 CST 2017
	 */
	int insertSelective(MenuPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table menu_permission
	 *
	 * @mbg.generated Tue May 23 01:24:41 CST 2017
	 */
	MenuPermission selectByPrimaryKey(Integer menuPermissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table menu_permission
	 *
	 * @mbg.generated Tue May 23 01:24:41 CST 2017
	 */
	int updateByPrimaryKeySelective(MenuPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table menu_permission
	 *
	 * @mbg.generated Tue May 23 01:24:41 CST 2017
	 */
	int updateByPrimaryKey(MenuPermission record);
}