package easy.work.source.module.rights.dao;

import java.util.List;

import easy.work.source.module.rights.pojo.Permission;
import easy.work.source.module.rights.query.PermissionQuery;

public interface PermissionDao {

	/**
	 * @Auther: zhuwt
	 * @Description: 根据角色pid 和 rid 查询
	 * @Date:2017年5月31日下午3:50:54
	 * @param rid
	 * @param mid
	 * @return
	 * @return int
	 */
	int selectPermissionByRidAndPid(Integer rid, Integer mid);

	/**
	 * @Auther: zhuwt
	 * @Description:批量删除
	 * @Date:2017年5月27日下午6:22:32
	 * @param ids
	 * @return
	 * @return int
	 */
	int deleteByIds(Integer[] ids);

	/**
	 * @Auther: zhuwt
	 * @Description: 查询角色下这个菜单所拥有的权限
	 * @Date:2017年5月26日下午5:16:57
	 * @param menuPermission
	 * @return
	 * @return List<Permission>
	 */
	List<Permission> selectPermissionByRidAndMid(Integer rid, Integer mid);

	/**
	 * @Auther: zhuwt
	 * @Description: 查询所有权限
	 * @Date:2017年5月23日上午1:03:41
	 * @param query
	 * @return
	 * @return List<Permission>
	 */
	List<Permission> selectAll(PermissionQuery query);

	/**
	 * 根据用户uid查询权限
	 * 
	 * @param uid
	 * @return
	 */
	List<Permission> selectByUserId(Integer uid);

	/**
	 * @Auther: zhuwt
	 * @Description:Role rid 查询
	 * @Date:2017年5月24日上午10:42:28
	 * @param query
	 * @return
	 * @return List<Permission>
	 */
	List<Permission> selectByRid(Integer rid);

	/**
	 * 根据菜单查询
	 * 
	 * @param mid
	 * @return
	 */
	List<Permission> selectByMenuId(int mid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table permission
	 *
	 * @mbggenerated Fri May 12 13:21:18 CST 2017
	 */
	int deleteByPrimaryKey(Integer pid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table permission
	 *
	 * @mbggenerated Fri May 12 13:21:18 CST 2017
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table permission
	 *
	 * @mbggenerated Fri May 12 13:21:18 CST 2017
	 */
	int insertSelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table permission
	 *
	 * @mbggenerated Fri May 12 13:21:18 CST 2017
	 */
	Permission selectByPrimaryKey(Integer pid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table permission
	 *
	 * @mbggenerated Fri May 12 13:21:18 CST 2017
	 */
	int updateByPrimaryKeySelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table permission
	 *
	 * @mbggenerated Fri May 12 13:21:18 CST 2017
	 */
	int updateByPrimaryKey(Permission record);
}