package easy.work.source.module.rights.dao;

import java.util.List;

import easy.work.source.module.rights.pojo.RolePremission;


public interface RolePremissionDao {
	

	/**
	 * @Auther: zhuwt  
	 * @Description: 查询pids
	 * @Date:2017年5月31日下午4:49:36
	 * @param rid
	 * @return  
	 * @return List<Integer>
	 */
	List<Integer> selectPidsByRidMenu(Integer rid);
	
	/**
	 * @Auther: zhuwt  
	 * @Description: 查询mid
	 * @Date:2017年5月31日下午4:49:36
	 * @param rid
	 * @return  
	 * @return List<Integer>
	 */
	List<Integer> selectPidsByRidPer(Integer rid);

	/**
	 * @Auther: zhuwt
	 * @Description: 删除该角色下所有的权限
	 * @Date:2017年5月23日下午10:40:26
	 * @param rid
	 * @return
	 * @return int
	 */
	int deleteByRid(Integer rid);

	/**
	 * @Auther: zhuwt
	 * @Description: 查询用户下的权限和菜单
	 * @Date:2017年5月27日上午11:10:15
	 * @param rid
	 * @param pid
	 * @return
	 * @return int
	 */
	int selectByRidAndPid(Integer rid, Integer pid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_premission
	 *
	 * @mbg.generated Tue May 23 21:28:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer rolePremissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_premission
	 *
	 * @mbg.generated Tue May 23 21:28:28 CST 2017
	 */
	int insert(RolePremission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_premission
	 *
	 * @mbg.generated Tue May 23 21:28:28 CST 2017
	 */
	int insertSelective(RolePremission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_premission
	 *
	 * @mbg.generated Tue May 23 21:28:28 CST 2017
	 */
	RolePremission selectByPrimaryKey(Integer rolePremissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_premission
	 *
	 * @mbg.generated Tue May 23 21:28:28 CST 2017
	 */
	int updateByPrimaryKeySelective(RolePremission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role_premission
	 *
	 * @mbg.generated Tue May 23 21:28:28 CST 2017
	 */
	int updateByPrimaryKey(RolePremission record);
}