package easy.work.source.module.rights.dao;

import easy.work.source.module.rights.pojo.UserRole;

public interface UserRoleDao {

	/**
	 * @Auther: zhuwt
	 * @Description: 根据用户uid修改用户角色
	 * @Date:2017年5月21日下午8:47:35
	 * @param userRole
	 * @return
	 * @return int
	 */
	int updateByUid(UserRole userRole);

	/**
	 * @Auther: zhuwt
	 * @Description: 根据用户uid删除数据
	 * @Date:2017年5月21日下午8:54:57
	 * @param uid
	 * @return
	 * @return int
	 */
	int deleteByUid(Integer uid);

	/**
	 * @Auther: zhuwt
	 * @Description: 删除角色时 删除角色和用户关联表
	 * @Date:2017年5月21日下午9:26:50
	 * @param rid
	 * @return
	 * @return int
	 */
	int deleteByRid(Integer rid);

	/**
	 * @Auther: zhuwt
	 * @Description:查询用户的角色id
	 * @Date:2017年5月27日上午11:25:56
	 * @param uid
	 * @return
	 * @return int
	 */
	int selectByUid(Integer uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_role
	 *
	 * @mbg.generated Sun May 21 13:51:19 CST 2017
	 */
	int deleteByPrimaryKey(Integer userRoleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_role
	 *
	 * @mbg.generated Sun May 21 13:51:19 CST 2017
	 */
	int insert(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_role
	 *
	 * @mbg.generated Sun May 21 13:51:19 CST 2017
	 */
	int insertSelective(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_role
	 *
	 * @mbg.generated Sun May 21 13:51:19 CST 2017
	 */
	UserRole selectByPrimaryKey(Integer userRoleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_role
	 *
	 * @mbg.generated Sun May 21 13:51:19 CST 2017
	 */
	int updateByPrimaryKeySelective(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_role
	 *
	 * @mbg.generated Sun May 21 13:51:19 CST 2017
	 */
	int updateByPrimaryKey(UserRole record);
}