package easy.work.source.module.rights.pojo;

public class MenuPermission {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_permission.menu_permission_id
	 * @mbg.generated  Tue May 23 01:24:41 CST 2017
	 */
	private Integer menuPermissionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_permission.mid
	 * @mbg.generated  Tue May 23 01:24:41 CST 2017
	 */
	private Integer mid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_permission.pid
	 * @mbg.generated  Tue May 23 01:24:41 CST 2017
	 */
	private Integer pid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_permission.menu_permission_id
	 * @return  the value of menu_permission.menu_permission_id
	 * @mbg.generated  Tue May 23 01:24:41 CST 2017
	 */
	public Integer getMenuPermissionId() {
		return menuPermissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_permission.menu_permission_id
	 * @param menuPermissionId  the value for menu_permission.menu_permission_id
	 * @mbg.generated  Tue May 23 01:24:41 CST 2017
	 */
	public void setMenuPermissionId(Integer menuPermissionId) {
		this.menuPermissionId = menuPermissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_permission.mid
	 * @return  the value of menu_permission.mid
	 * @mbg.generated  Tue May 23 01:24:41 CST 2017
	 */
	public Integer getMid() {
		return mid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_permission.mid
	 * @param mid  the value for menu_permission.mid
	 * @mbg.generated  Tue May 23 01:24:41 CST 2017
	 */
	public void setMid(Integer mid) {
		this.mid = mid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_permission.pid
	 * @return  the value of menu_permission.pid
	 * @mbg.generated  Tue May 23 01:24:41 CST 2017
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_permission.pid
	 * @param pid  the value for menu_permission.pid
	 * @mbg.generated  Tue May 23 01:24:41 CST 2017
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}
}